blank_issues_enabled: false
contact_links:
  - name: E-mail contact
    url: mailto:styzwave@gmail.com
    about: Feel free to mail us regarding any issue or something related to Vipin Project.
  - name: Discord community
    url: https://discord.gg/Cnm62fhc8f
    about: Contact us via our Discord community.